### ISSUE TITLE
패턴학습-알고리즘(Ahn)

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#11]
1.머신러닝용 엔진 찾아보기
2.엔진 설치 및 테스팅
3.주문리스트 검토

**Comment by KwangEun** [comment]
1. TensorFlow Machine learning algorithm - [tensorflow.org](http://tensorflow.org)
   - Google's Machines Intelligence 연구 그룹의 Google Brain Team에서 진행되었던 프로젝트, 현재도 계속 발전 중
   - 리눅스 기반, Python 2 혹은 3 , CUDA Toolkit 7 & [cuDNN](https://developer.nvidia.com/cudnn) V4 사용 권장
2. PredictionIO - [PredictionIO](https://prediction.io/), [GitHub](https://github.com/apache/incubator-predictionio)

PredictionIO
![image](https://cloud.githubusercontent.com/assets/10568401/17201879/280f4086-54cf-11e6-8829-125b97a22a1f.png)

Event Sever
![image](https://cloud.githubusercontent.com/assets/10568401/17201893/7dce7032-54cf-11e6-843c-3c724304c44a.png)
- 메인 사이트의 https의 요청을 http로 전환하여 요청하면 정상 접속 가능
- 아파치에서 후원하는 아파치 기반의 머신러닝 플랫폼
- 서버를 생성하고 App Key, App Secret를 사용하여 앱과 연결
- 데이터베이스를 이벤트 서버로 사용
- 필요한 엔진을 이식하여 사용 가능
- 리눅스 기반, Java 1.8, MySQL 혹은 PostgreSQL
- 데이터를 REST API, php, Java, RUBY
1. Seldon - [Seldon](http://www.seldon.io/), [GitHub](https://github.com/SeldonIO/seldon-server)
   - 매우 활발한 개발
   - 개별 서버 이외에 Aws, Google Cloud Platform , Azure에 이식하여 사용도 가능
   - python 으로 구동되는 서버환경
2. Smile - [Smile](http://haifengl.github.io/smile/), [GitHub](https://github.com/haifengl/smile)
   
   ## \- 통계적 머신러닝 엔진
3. Amazon Machine Learning - [AML](https://aws.amazon.com/ko/machine-learning/)
   - 미리 정립된 알고리즘과 데이터들을 사용하여 입력에 대한 자동화된 결과 값을 보여줌
   - 사용양에 비례하여 돈을 지불해야됨.

**Comment by KwangEun** [comment]
![img_20160727_152759](https://cloud.githubusercontent.com/assets/10568401/17204525/fe1c5630-54e0-11e6-9152-70b2a5d35a48.jpg)
