### ISSUE TITLE
패턴학습 - Algorithm(이성원)

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#4]
패턴학습 : 알고리즘 사용 사례 조사

**Comment by sadcookie** [comment]
file:///C:/Users/sung/Downloads/microsoft-machine-learning-algorithm-cheat-sheet-v6.pdf

**Comment by sadcookie** [comment]
[microsoft-machine-learning-algorithm-cheat-sheet-v6.pdf](https://github.com/PlantingTeam/SmartPlanting/files/362937/microsoft-machine-learning-algorithm-cheat-sheet-v6.pdf)
Machine Learning 기초 : http://whydsp.org/237
                                        https://azure.microsoft.com/ko-kr/documentation/articles/machine-learning-algorithm-choice/

**Comment by sadcookie** [comment]
![image](https://cloud.githubusercontent.com/assets/17808301/16830320/1a7a1a1e-49d9-11e6-9c30-0652d6b04e09.png)

**Comment by sadcookie** [comment]
![image](https://cloud.githubusercontent.com/assets/17808301/16830487/582a5300-49da-11e6-8d17-dfa6c69e0ce0.png)

**Comment by sadcookie** [comment]
![image](https://cloud.githubusercontent.com/assets/17808301/16830529/919a40be-49da-11e6-86e1-482c82171683.png)

![image](https://cloud.githubusercontent.com/assets/17808301/16830510/788611c0-49da-11e6-933c-0c633536ce33.png)
