### ISSUE TITLE
장치 - 센서부 (안광은)

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#6]
센서 : 소형 작물 센서 리스트 및 활용방법
MinT : 소개

**Comment by KwangEun** [comment]
식물 성장 
참고 : [Wikipedia](https://ko.wikipedia.org/wiki/%EB%B9%84%EB%A3%8C)

대기 
- 질소 : 식물의 실질적인 몸체를 구성하게 되는 중요한 요소.
- 산소 : 밤에 호흡을 위하여 필요 
- 이산화탄소 : 낮에 광합성을 위하여 필요
  토양
- 질소 // 생장 초기에 많이 이용, 황산암모늄, 요소, 석회질소, 질산 암모늄
- 인산
- 칼륨 
  /\* 토양은 위의 물질이 쉽게 공급 부족을 겪을 수 있다. 비료의 3요소*/
- 칼슘
  /\* 그 다음으로 부족해지기 쉬운 요소인 칼슘까지 하여 비료의 4요소*/ 
- 황
- 마그네슘
- 물 /\* 사막 지대의 경우 물 또한 공급 부족을 겪을 수 있다. */

조건 
- 부식토 및 점토의 질
- 토양 수분 함유량
- 온도

**Comment by KwangEun** [comment]
센서의 종류

광센서/이미지센서 
- 포토다이오드
- 포토트랜지스터 : 빛을 받으면 투과되는 전류가 많아지는 센서
- Cds셀 : 자연광 감지
- 주변광센서 : 빛의 투사량(LUX)을 측정할 수 있는 센서

위치인식/MEMS센서
- 수위센서 : 물이 전류를 방전시키는 원리로 측정

가스/공기질 센서
- O2/O3센서 : 산소 센서, (10만원대가 넘어감)
- CO/CO2센서 : 공기중 CO2를 측정 NDIR: 비 선형 적외선 방식

온도/습도/환경센서
- 온도/습도센서 : 
- 먼지센서 : 레이저를 사용하여 0.3마이크로 미터 이상의 입자를 검출

써미스터 : 온도에 따라 변화하는 저항
- NTC써미스터 : 온도 증가 = 저항 증가
- PTC써미스터 : 온도 증가 = 저항 감소
