### ISSUE TITLE
장치 - 센서부(이제호)

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#7]
github : 가입, 사용법 숙지

**Comment by Jeho0216** [comment]
github 가입완료. git 설치완료.
git, github 개념 확인(목적, Commit, Branch, Merge)
SourceTree를 이용해서 GUI환경에서 git 관리 방법.
Commit 추가, 되돌리기, Branch 생성, 이동, 병합, Github와 연결
