### ISSUE TITLE
장치 - 제어부 (백인걸)

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#8]
통신 : 아두이노-라즈베리 양방향 통신
모터 : 모터동작과 응용방식 조사

**Comment by Geol2** [comment]
모터 : 기본 동작 원리
- "전동기" 라고도 부른다. (모터 = 전동기)
- 개념
  - ![3](https://cloud.githubusercontent.com/assets/20119461/16749217/91180afa-4803-11e6-92f1-80f7a12ed07b.PNG) (출처 : 네이버 이미지 검색)
  - 자기장 : 자석이나 전류 또는 시간에 따라 변화하는 전기장에 의해 그 주위에 자기력이 작용하는 공간을 만든다. 그 공간을 자기장이라 한다. (자계, 자장)
  - 자기장의 방향은 자기장 내에 있는 나침반 자침의 N극이 받는 힘의 방향. = 자기력선.
  - 자기력선은 N극에서 나와 S극을 향한다..
- 원리
  - 자석의 원리를 이용함. S극(파란), N극(빨강) -  서로 같은 극은 밀고 다른 극은 당긴다.
  - 더 자세한 내용은 http://blog.daum.net/gahna61/227 참고
  - 플레밍의 왼손 법칙. ( 플레밍의 오른손 법칙은 발전기의 원리. - 힘을 주어 전기를 생산. ) 
  - 전동기는 전류를 흘리면 힘이 생김. 따라서 전류를 흘려서 힘이 생기는 방향을 찾을때 왼손법칙.
    ![1](https://cloud.githubusercontent.com/assets/20119461/16747797/953359c6-47fb-11e6-8666-56cebe15c522.PNG) (출처 : 네이버 검색)
  - 자속  ≒ 자계 = 자기장의 방향
  - 힘(F)  = 자기장 세기(B) \* 전류의 세기(I)  \* 도선의 길이 (L)   =>      F = BIL  
  - 뉴턴(N) = 테슬라(T) \* 암페어(A) \* 미터(m)
  - 1미터 도선에 1암페어의 전류를 흐를 때, 1뉴턴의 힘을 받게 하는 자기장을 1테슬라 라고 한다.
- 자료 참고 : 네이버 지식 백과.  구글.

모터는 대표적으로 AC모터와 DC모터가 있다.
- AC모터
  - 교류 전원 (가정용 220V)에 사용되는 모터.
  - 저소음, 저진동과 반영구적 수명, 안정적인 성능이 장점
- DC모터
  - 직류 전원 (배터리)을 사용하는 모터.
  - 기동 토크가 크고, 효율이 높으며 가격이 저렴하다는 장점.

모터의 종류는 매우 다양하다고 함. 급수 펌프와 수중 모터 펌프 등에 대해 조사를 해 보았다.
- 급수 펌프
  -  ![4](https://cloud.githubusercontent.com/assets/20119461/16802045/62f68908-4939-11e6-9473-ea0512c632eb.PNG)
    (출처 : 네이버 물 백과사전)
  - 급수 설비에 사용되는 펌프로 공장의 용수 공급 및 음용수의 급수에 사용됨.
  - 밸브에 따라 유량 조절이 많이 변화가 된다. ( 수동밸브 : 일정한 편 , 유압밸브 : 동력을 이용. 유량의 변화가 심한 편.)
- 급수방식에 따라 수위 조절 방식과 유량 조절 방식이 있다.
  - 수위 조절 방식은 고가 수조에 급수하는 방식 : 밸브로 조절.
  -  아파트, 건물, 공장의 용수 저장용 등으로 많이 사용 하여 수위의 낙차를 이용하여 자연 낙하 급수.
- 유량 조절 방식
  - 공장 용수로 사용하기 위하여 급수하는 시스템.
  - 조수조의 수위에 따라 급수 펌프의 기동, 정지를 하는 방식.
  - 밸브의 개폐에 따라 급수량을 조절하는 방식.

수중 모터 펌프
 -![6](https://cloud.githubusercontent.com/assets/20119461/16802273/ee0755ee-493a-11e6-80b3-8d53187d3a25.PNG)
- 회전부가 수중에 있어 소음과 진동이 없고, 구조가 간단해서 설치와 취급이 용이.
- 주로 상, 하수도나 급배수, 가정 우물 등에 많이 이용되는 펌프이다.
- 구조는 원심 펌프, 다단 터빈 펌프, 축류 펌프, 오수 펌프, 블레이드리스 펌프 등 여러 가지가 사용.

가압 펌프
- 고지대에 물을 보낼 때 주로 사용되는 것으로, 송수관로에 압력을 높이기 위해 설치하는 펌프
- http://nanakono.tistory.com/35

**Comment by vertex50** [comment]
급수 모터 관련해서 조사 한번 해보시겠어요?
사용될 모터가 급수 모터여서 어떤식으로 물을 끌어올리는지 등이 궁금하네요!!

**Comment by Geol2** [comment]
시리얼 통신
- 1바이트(컴퓨터 기억장치의 크기 단위) 의 데이터를 주고 받는 직렬 통신.
- SPI, I2C,  UART 통신들도 시리얼 통신의 일종.
- 흔히 아두이노에서의 시리얼 통신은 UART 통신을 의미한다.
- 아두이노 -----(1000 0010) -----> 컴퓨터

Baudrate (보레이트)
- 시리얼 통신의 속도

아두이노 우노에서 0부터 1023까지 값을 0.5초 간격으로 출력하는 코드..
 -![-](https://cloud.githubusercontent.com/assets/20119461/16826284/281b12fc-494a-11e6-9627-e8e6ca7b440a.png)

아두이노 우노에서 시리얼 통신으로 보낸 값을 라즈베리 파이에서 반복하여 읽어서 10을 곱해서 출력하는 코드..
-![default](https://cloud.githubusercontent.com/assets/20119461/16826278/1b2dd23c-494a-11e6-91c1-e512fd85fc3f.png)

Putty(SSH)로 라즈베리파이에 접속한 화면에서 아래와 같이 SerialRead1.py를 실행하면
아두이노 우노에서 전송된 값에 계산된 (*10) 값이 화면에 순서대로 표시됩니다.
- ![pyton](https://cloud.githubusercontent.com/assets/20119461/16826502/cba637e4-49b8-11e6-9fe6-6c31585ccf6e.PNG)
