### ISSUE TITLE
장치-제어부

### ISSUE THREAD

**Issue by vertex50** [PlantingTeam/SmartPlanting#9]
1.보유 급수펌프 테스트 및 사용(모터구동)
2.통신환경 파이썬 선 작동시 버그가 없는지 확인
3.주문할 펌프장비 선정

**Comment by Geol2** [comment]
[스마트 플랜팅 - 모터 제어부.zip](https://github.com/PlantingTeam/SmartPlanting/files/387855/-.zip)
